# Generated by Django 5.2.4 on 2026-02-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('analyzed_skills', models.JSONField(blank=True, default=list)),
                ('experience_years', models.FloatField(default=0.0)),
                ('education', models.TextField(blank=True, null=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_data', to='jobs.jobapplication')),
            ],
        ),
    ]
