# Generated by Django 5.2.4 on 2026-02-11 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('requirements', models.TextField()),
                ('application_deadline', models.DateField()),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('rank_score', models.FloatField(default=0.0)),
                ('groq_rank', models.FloatField(default=0.0)),
                ('bert_similarity', models.FloatField(default=0.0)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('total_experience', models.CharField(blank=True, max_length=100)),
                ('cgpa', models.CharField(blank=True, max_length=10, null=True)),
                ('project_categories', models.JSONField(blank=True, default=list)),
                ('custom_model_score', models.FloatField(default=0.0)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobRankingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa_weight', models.PositiveIntegerField(default=0)),
                ('skills_weight', models.PositiveIntegerField(default=0)),
                ('experience_weight', models.PositiveIntegerField(default=0)),
                ('project_weight', models.PositiveIntegerField(default=0)),
                ('llm_weight', models.PositiveIntegerField(default=0)),
                ('bert_weight', models.PositiveIntegerField(default=0)),
                ('custom_model_weight', models.PositiveIntegerField(default=0)),
                ('shortlist_count', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_config', to='jobs.job')),
            ],
        ),
    ]
