# Generated by Django 5.2.4 on 2026-04-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobapplication_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='gradio_analysis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='gradio_match_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
