# Generated by Django 5.2.4 on 2026-04-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_gradio_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='gradio_match_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
