# Generated by Django 5.2.4 on 2026-04-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedresume',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
