# Generated by Django 5.2.4 on 2026-04-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0002_uploadedresume_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedresume',
            name='file_hash',
        ),
    ]
