# Generated by Django 5.2.4 on 2026-04-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
