# Generated by Django 5.2.4 on 2026-02-11 13:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('requires_answer_key', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('written', 'Written Assessment'), ('live', 'Live Interview'), ('mixed', 'Mixed (Written + Live)')], max_length=20)),
                ('title', models.CharField(default='Untitled Interview', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interviews', to=settings.AUTH_USER_MODEL)),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviews', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.job')),
                ('categories', models.ManyToManyField(blank=True, related_name='interviews', to='interview.interviewcategory')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_chat_sessions', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interview.interviewchatsession')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preparations', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preparations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=20)),
                ('points', models.PositiveIntegerField(default=10)),
                ('time_limit_minutes', models.PositiveIntegerField(default=5)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_option_indices', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('auto_score_enabled', models.BooleanField(default=False)),
                ('hr_answer', models.TextField(blank=True, help_text='Correct answer (visible only to HR)')),
                ('hr_answer_notes', models.TextField(blank=True, help_text='Explanation/grading criteria')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interviewcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.questiontype')),
            ],
            options={
                'ordering': ['category', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestionGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_used', models.TextField()),
                ('generated_questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_generations', to='interview.interviewpreparation')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('expected_answer_text', models.TextField(blank=True, null=True)),
                ('expected_keywords', models.JSONField(blank=True, null=True)),
                ('auto_score_enabled', models.BooleanField(default=False)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='interview.interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('code_snippet', models.TextField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='candidate_answers/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('auto_score', models.FloatField(blank=True, null=True)),
                ('hr_score', models.FloatField(blank=True, null=True)),
                ('hr_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.interviewquestionset')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('performance_level', models.CharField(blank=True, max_length=50)),
                ('finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_results', to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='interview.interview')),
            ],
        ),
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('total_questions', models.IntegerField(default=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockInterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveIntegerField()),
                ('question', models.JSONField()),
                ('answer', models.TextField()),
                ('feedback', models.TextField()),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.mockinterviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('estimated_time_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_modules', to='interview.interviewcategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreparationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.preparationmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIPreparationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_content', models.JSONField()),
                ('model_used', models.CharField(default='llama-3.1-8b-instant', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preparation_sessions', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preparation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Interview Preparation Session',
                'verbose_name_plural': 'AI Interview Preparation Sessions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['hr_user', 'status'], name='interview_i_hr_user_a64aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['candidate', 'status'], name='interview_i_candida_b44e83_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['job', 'status'], name='interview_i_job_id_99297b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewpreparation',
            unique_together={('user', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='interviewquestionset',
            unique_together={('interview', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='candidateanswer',
            unique_together={('question_set', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='interviewresult',
            unique_together={('interview', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='mockinterviewanswer',
            unique_together={('session', 'question_index')},
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['category', 'difficulty'], name='interview_i_categor_90d9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['question_type', 'is_active'], name='interview_i_questio_5115ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpreparationprogress',
            unique_together={('user', 'module')},
        ),
    ]
