# Generated by Django 5.2.4 on 2026-04-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewpreparation',
            name='last_more_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='more_generate_count',
            field=models.IntegerField(default=0),
        ),
    ]
