# Generated by Django 5.2.4 on 2026-04-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewpreparation_last_more_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewchatsession',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewchatsession',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
