# Generated by Django 5.2.4 on 2026-04-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_interviewchatsession_messages_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewchatsession',
            name='messages_count',
        ),
        migrations.RemoveField(
            model_name='interviewchatsession',
            name='tokens_used',
        ),
    ]
