version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentmatch_web
    command: /app/entrypoint.sh
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
